"""
Tests for LLM-based reading notes generation.

Tests the generation of IMRaD-structured reading notes using LiteLLM.
"""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import json


class TestNotesGeneration:
    """Test suite for LLM notes generation functionality."""

    @pytest.mark.asyncio
    async def test_notes_generation(self, mock_litellm, test_imrad_structure):
        """
        Test generating IMRaD structured notes.

        Verifies that:
        - Notes contain all IMRaD sections
        - Content is properly structured
        - LLM is called with correct prompt
        """
        # Arrange: Setup mock response
        expected_notes = """# 研究背景

本文研究了人工智能在医学影像分析中的应用。随着深度学习技术的发展，
医学影像诊断的准确性得到了显著提升。

# 研究方法

研究使用了卷积神经网络（CNN）对医学影像进行分类。
数据集包含10,000张来自三家医院的医学影像。

# 研究结果

模型在测试集上达到了95%的准确率，显著优于传统的机器学习方法。
F1分数为0.94，精确率为93%，召回率为96%。

# 结论

研究表明人工智能可以有效辅助医学影像诊断。未来的工作将集中在
扩展到三维影像分析。"""

        mock_litellm.acompletion.return_value = {
            "choices": [{"message": {"content": expected_notes}}],
            "usage": {"prompt_tokens": 1000, "completion_tokens": 500, "total_tokens": 1500}
        }

        # Act: Generate notes
        with patch('litellm.acompletion', mock_litellm.acompletion):
            response = await mock_litellm.acompletion(
                model="gpt-4",
                messages=[{"role": "user", "content": "Generate notes"}]
            )
            generated_notes = response["choices"][0]["message"]["content"]

            # Assert: Verify notes structure
            assert "# 研究背景" in generated_notes or "# Introduction" in generated_notes
            assert "# 研究方法" in generated_notes or "# Methods" in generated_notes
            assert "# 研究结果" in generated_notes or "# Results" in generated_notes
            assert "# 结论" in generated_notes or "# Conclusion" in generated_notes

    @pytest.mark.asyncio
    async def test_markdown_export(self, mock_litellm):
        """
        Test exporting notes as Markdown.

        Verifies that:
        - Notes are valid Markdown
        - Headers are properly formatted
        - Content is well-structured
        """
        markdown_content = """# Paper Reading Notes

## Paper Information
- **Title**: Deep Learning for Medical Imaging
- **Authors**: Zhang San, Li Si
- **Published**: 2024

## 研究背景 (Introduction)

Medical image analysis using deep learning.

## 研究方法 (Methods)

CNN architecture with 12 layers.

## 研究结果 (Results)

95% accuracy achieved.

## 结论 (Conclusion)

AI is effective for medical imaging.

---

*Generated by ScholarAI on 2024-01-15*"""

        # Verify Markdown structure
        assert markdown_content.startswith("#")
        assert "##" in markdown_content  # Has subheaders
        assert "**" in markdown_content  # Has bold text

        # Verify IMRaD sections
        assert any(section in markdown_content for section in [
            "研究背景", "Introduction", "背景"
        ])
        assert any(section in markdown_content for section in [
            "研究方法", "Methods", "方法"
        ])
        assert any(section in markdown_content for section in [
            "研究结果", "Results", "结果"
        ])
        assert any(section in markdown_content for section in [
            "结论", "Conclusion", "总结"
        ])

    @pytest.mark.asyncio
    async def test_notes_versioning(self):
        """
        Test creating new version on regeneration.

        Verifies that:
        - New version is created when regenerating
        - Previous version is preserved
        - Version history is tracked
        """
        # Version 1
        version_1 = {
            "version_id": "v1",
            "content": "First version of notes",
            "created_at": "2024-01-15T10:00:00Z",
            "is_current": False,
        }

        # Version 2 (regenerated)
        version_2 = {
            "version_id": "v2",
            "content": "Updated version with user feedback",
            "created_at": "2024-01-15T11:00:00Z",
            "is_current": True,
            "previous_version": "v1",
        }

        # Verify versioning
        assert version_1["version_id"] != version_2["version_id"]
        assert version_2["is_current"] is True
        assert version_1["is_current"] is False
        assert version_2.get("previous_version") == "v1"

    @pytest.mark.asyncio
    async def test_notes_with_large_paper(self, mock_litellm):
        """
        Test handling papers exceeding context window limits.

        Verifies that:
        - Content is truncated appropriately
        - Key information is preserved
        - LLM call doesn't fail with large input
        """
        # Simulate large paper content (>15000 chars)
        large_content = "This is paper content. " * 1000  # ~24k characters

        assert len(large_content) > 15000

        # Expected: content should be truncated
        max_chars = 15000
        truncated = large_content[:max_chars]

        assert len(truncated) <= max_chars

        # Truncation should not break mid-word ideally
        # (implementation detail, but good to verify)

    @pytest.mark.asyncio
    async def test_notes_generation_prompt(self, mock_litellm):
        """
        Test that correct prompt is sent to LLM.

        Verifies that:
        - Prompt includes paper content
        - IMRaD structure is requested
        - Language matches paper language
        """
        paper_content = "Sample paper content in Chinese."

        expected_prompt_parts = [
            "IMRaD",
            "研究背景",
            "研究方法",
            "研究结果",
            "结论",
        ]

        # Verify prompt would contain expected parts
        assert "研究" in paper_content or "医学" in paper_content

    @pytest.mark.asyncio
    async def test_notes_generation_error_handling(self, mock_litellm):
        """
        Test handling of LLM API errors.

        Verifies that:
        - Errors are caught and handled
        - User-friendly error message is returned
        """
        # Simulate API error
        mock_litellm.acompletion.side_effect = Exception("API Error: Rate limit exceeded")

        with patch('litellm.acompletion', mock_litellm.acompletion):
            try:
                await mock_litellm.acompletion(model="gpt-4", messages=[])
                assert False, "Should have raised exception"
            except Exception as e:
                assert "API Error" in str(e)

    @pytest.mark.asyncio
    async def test_notes_language_detection(self):
        """
        Test automatic language detection for notes.

        Verifies that:
        - Chinese papers get Chinese notes
        - English papers get English notes
        """
        chinese_content = "本研究探讨了人工智能在医学影像中的应用。"
        english_content = "This study explores AI applications in medical imaging."

        # Verify content languages
        assert any('\u4e00' <= char <= '\u9fff' for char in chinese_content)
        assert chinese_content != english_content


class TestNotesStorage:
    """Test suite for notes storage and retrieval."""

    def test_save_notes(self):
        """
        Test saving notes to database.

        Verifies that:
        - Notes are stored with paper ID
        - Version is tracked
        - Timestamps are recorded
        """
        notes_record = {
            "id": "notes-001",
            "paper_id": "paper-123",
            "version": 1,
            "content": "# Reading Notes\n\nContent here...",
            "language": "zh",
            "created_at": "2024-01-15T10:00:00Z",
            "updated_at": "2024-01-15T10:00:00Z",
            "generated_by": "gpt-4",
        }

        assert notes_record["paper_id"] is not None
        assert notes_record["version"] >= 1
        assert notes_record["content"] is not None

    def test_retrieve_notes(self):
        """
        Test retrieving notes by paper ID.

        Verifies that:
        - Current version is retrieved by default
        - Specific version can be requested
        - All versions can be listed
        """
        paper_id = "paper-123"
        current_version = {
            "id": "notes-002",
            "paper_id": paper_id,
            "version": 2,
            "is_current": True,
        }

        previous_version = {
            "id": "notes-001",
            "paper_id": paper_id,
            "version": 1,
            "is_current": False,
        }

        assert current_version["paper_id"] == paper_id
        assert current_version["version"] > previous_version["version"]

    def test_update_notes(self):
        """
        Test updating notes with user modifications.

        Verifies that:
        - User edits are saved
        - New version is created
        - Original generated version is preserved
        """
        # Original generated notes
        original = {
            "version": 1,
            "content": "Original generated content",
            "is_user_modified": False,
        }

        # User modified version
        modified = {
            "version": 2,
            "content": "User modified content",
            "is_user_modified": True,
            "modification_note": "Added more detail to methods section",
        }

        assert modified["is_user_modified"] is True
        assert modified["version"] > original["version"]


class TestNotesExport:
    """Test suite for notes export functionality."""

    def test_export_markdown(self):
        """Test exporting notes as Markdown file."""
        notes_content = "# Notes\n\nContent"

        # Markdown should be valid
        assert notes_content.startswith("#")
        assert len(notes_content) > 0

    def test_export_pdf(self):
        """Test exporting notes as PDF."""
        # PDF export would require additional libraries
        # This test defines the expected behavior
        notes_content = "# Notes\n\nContent"

        assert notes_content is not None

    def test_export_json(self):
        """Test exporting notes as JSON."""
        notes_data = {
            "paper_id": "paper-123",
            "sections": {
                "introduction": "Intro content",
                "methods": "Methods content",
                "results": "Results content",
                "conclusion": "Conclusion content",
            },
            "metadata": {
                "generated_at": "2024-01-15T10:00:00Z",
                "model": "gpt-4",
            }
        }

        json_str = json.dumps(notes_data, ensure_ascii=False)
        assert json_str is not None
        assert "paper_id" in json_str

    def test_export_with_custom_template(self):
        """Test exporting with custom template."""
        template = """# {{paper_title}}

## Reading Notes

{{notes_content}}

---
Generated on {{date}}"""

        assert "{{paper_title}}" in template
        assert "{{notes_content}}" in template


class TestNotesGenerationPrompts:
    """Test suite for prompt engineering."""

    def test_prompt_structure(self):
        """
        Test that prompts follow expected structure.

        Verifies:
        - System message sets context
        - User message contains paper content
        - IMRaD sections are requested
        """
        system_prompt = """You are an academic research assistant. Your task is to
        generate structured reading notes from academic papers.
        Follow the IMRaD structure: Introduction, Methods, Results, Conclusion.
        Write in the same language as the paper."""

        assert "IMRaD" in system_prompt or "academic" in system_prompt
        assert len(system_prompt) > 0

    def test_prompt_with_paper_content(self):
        """Test prompt that includes paper content."""
        paper_content = "Sample paper content..."

        user_prompt = f"""Please generate reading notes for the following academic paper:

{paper_content}

Generate notes in IMRaD format covering:
1. 研究背景 / Introduction
2. 研究方法 / Methods
3. 研究结果 / Results
4. 结论 / Conclusion"""

        assert paper_content in user_prompt
        assert "IMRaD" in user_prompt or "研究背景" in user_prompt

    def test_prompt_token_count(self):
        """Test that prompt stays within token limits."""
        # Typical token limit for GPT-4 is 8k-32k
        max_tokens = 8000

        # Estimate: 1 token ~= 4 characters for English
        max_chars = max_tokens * 3  # Conservative estimate

        sample_prompt = "A" * 10000  # 10k characters

        assert len(sample_prompt) <= max_chars


class TestNotesEdgeCases:
    """Test edge cases for notes generation."""

    @pytest.mark.asyncio
    async def test_empty_paper_content(self):
        """Test handling of empty paper content."""
        empty_content = ""

        assert len(empty_content) == 0

    @pytest.mark.asyncio
    async def test_very_short_paper(self):
        """Test handling of very short papers."""
        short_content = "This is a short abstract."

        assert len(short_content) < 100

    @pytest.mark.asyncio
    async def test_paper_without_imrad(self):
        """Test handling of papers without clear IMRaD structure."""
        non_imrad_content = "This is a review article without standard sections."

        # Should still generate notes
        assert len(non_imrad_content) > 0

    @pytest.mark.asyncio
    async def test_llm_timeout(self):
        """Test handling of LLM timeout."""
        # Simulate timeout
        timeout_error = TimeoutError("LLM request timed out")

        assert isinstance(timeout_error, TimeoutError)

    @pytest.mark.asyncio
    async def test_invalid_llm_response(self):
        """Test handling of invalid LLM response."""
        invalid_response = {"error": "Invalid response format"}

        assert "error" in invalid_response
